project:
  output-dir: docs
  type: website

website:
  title: "MattMeister.com"
  site-url: "https://www.mattmeister.com"
  favicon: favicon/dog.png     # Removed the leading slash
  navbar:
    raw-html: true
    search: false
    logo: favicon/dog.png       # Also removed leading slash
    background: primary
    left:
      - text: "<span class='btn btn-yellow'>Home</span>"
        href: index.qmd
      - text: "<span class='btn btn-yellow'>Blog</span>"
        href: soap_box.qmd
      - text: "<span class='btn btn-yellow'>Papers</span>"
        href: papers.qmd
      - text: "<span class='btn btn-yellow'>Code & Data</span>"
        href: code_data.qmd
      - text: "<span class='btn btn-yellow'>Reviews HOF</span>"
        href: reviews_hall_of_fame.qmd
  google-analytics: "G-KEYFNVVL8D"

format:
  html:
    theme: styles/bootswatch_with_yellow_green.scss
    toc: true

resources:
  - favicon/dog.png

editor: visual

