---
title: "Code & Data"
format:
  html:
    embed-resources: true
    smooth-scroll: true
    toc: true
    page-layout: full
    search: false
editor: source
---

::: text-center
These ain't perfect... Please let me know of any errors you find!
:::

## Web Scraping

### &nbsp;&nbsp;&nbsp;&nbsp;[Tripadvisor]("https://www.tripadvisor.com") 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reviews, questions, and answers

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mattmeist/scrape_tripadvisor_reviews" class="btn btn-yellow me-2" role="button" target="_blank">Scraping Code</a> <a href="https://www.dropbox.com/scl/fo/5pvyqayw36q3x3cnrddtr/AB2lPmt258ZKJMmcSIhJeWs?rlkey=khfd5g4e6odgrna4uyw10nlaj&dl=0" class="btn btn-yellow" role="button">Data</a>

### &nbsp;&nbsp;&nbsp;&nbsp;[REI]("https://www.rei.com")

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reviews

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mattmeist/scrape_rei_ratings" class="btn btn-yellow me-2" role="button" target="_blank">Scraping Code</a> <a href="https://www.dropbox.com/scl/fi/3d91nq9baxo4n1z7zbp45/REI_Reviews_All.csv?rlkey=3dxwwcvguqj1v32wbb6kg2ihg&dl=0" class="btn btn-yellow" role="button">Raw Data</a> <a href="https://www.dropbox.com/scl/fi/rnotwsyzytkmsu28aoqfc/NOAA_160101_231127.csv.zip?rlkey=sthp13a800m6qbi6cj0yuj5f3&dl=0" class="btn btn-yellow" role="button">Weather Data</a> <a href="https://www.dropbox.com/scl/fi/t9k8kq8kqfl0td78t4t0e/REI_Final.csv?rlkey=r78utumm92wm31qpu4o9ja60v&dl=0" class="btn btn-yellow" role="button">Merged Data</a>
    

### &nbsp;&nbsp;&nbsp;&nbsp;[Vrbo]("https://www.vrbo.com")

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Listings information and reviews

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mattmeist/scrape_vrbo_ratings" class="btn btn-yellow me-2" role="button" target="_blank">Scraping Code</a> <a href="https://www.dropbox.com/scl/fo/5pdne7kkq9jc64ybdo82l/h?rlkey=6oti6vn44830byjg8ry77ryn1&dl=0" class="btn btn-yellow" role="button">Data</a> 

### &nbsp;&nbsp;&nbsp;&nbsp;[BestBuy]("https://www.BestBuy.com")

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aggregated review information (might add to this eventually)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.dropbox.com/scl/fi/54w55kxc926g4scjyv64f/Best-Buy-Scrape.ipynb?rlkey=ytjr5vuybztpd5xkszhvy3zhp&dl=0" class="btn btn-yellow me-2" role="button" target="_blank">Scraping Code</a> <a href="https://www.dropbox.com/scl/fi/p2imn77f86qyz04ppz08i/bestbuy_overalls.csv?rlkey=ibathooa3fa075cgh5v0srv72&dl=0" class="btn btn-yellow" role="button">Data</a> 

### &nbsp;&nbsp;&nbsp;&nbsp;[ESPN.com March Madness]("https://fantasy.espn.com/games/tournament-challenge-bracket-2025")

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brackets for men's and women's tournaments

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mattmeist/scrape_espn_brackets" class="btn btn-yellow me-2" role="button" target="_blank">Scraping Code</a> <a href="https://www.dropbox.com/scl/fo/2kh9pf9q7u9nt2q3o8ofu/h?rlkey=29pkav0csspgnm1bqytqxvebp&dl=0" class="btn btn-yellow" role="button">Data</a> 


## Other

### Fast and Flexible Specification Curve

The popular `specr` package in R is good. However, `specr` is not super flexible---it does not support fixed-effect regressions, and mixed-effect regressions take some work.

I wanted to create a package that would build on `specr` while being more user-friendly. To that end, I'm working on this set of functions, which I've given the bad title of `specster`:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mattmeist/specster" class="btn btn-yellow me-2" role="button" target="_blank">Code</a>

The current code supports:

-   Four common models: OLS Linear Regression, Logistic Regression, Fixed-Effect Regression, and Linear Mixed-Effect Regression (i.e., `lm`, `glm`, `lfe::felm`, and `lmerTest::lmer` in R)
-   Setup of models
-   Multicore processing to speed up computation
-   Graphing with `ggplot2`

Citations:

-   `specr` package, which my repository borrows some from: <https://github.com/masurp/specr>
-   Specification Curve Analysis: Simonsohn, U., Simmons, J.P. & Nelson, L.D. (2020). Specification curve analysis. *Nature Human Behaviour*, 4, 1208--1214. [https://doi.org/10.1038/s41562-020-0912-z](doi)

### Lasso Regression Example

Just an example of Lasso Regression with a short explanation.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://drive.google.com/file/d/1Mm9Wp5cB_JUSJ9AJQV4hwGDoF8g5An_R/view?usp=sharing" class="btn btn-yellow me-2" role="button" target="_blank">.html</a>

### Mediation Model Plotting (Work-in-Progress)

This function will draw you a mediation model in `ggplot` in R. It ain't awesome, but mediation is kind of silly anyways.\
I plan to keep adding to it, as it can only do super simple mediation now.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mattmeist/mediation_plots" class="btn btn-yellow me-2" role="button" target="_blank">Code</a>