---
title: "Teaching"
search: false
format:
  html:
    toc: true
    page-layout: full
editor: source
---

## Experience

This [links to a folder](https://www.dropbox.com/scl/fo/t1bfk82fxow328r71g1g3/ALdlLah6QMCZ-WGJ7rJLleg?rlkey=yjmitbd8dxvjn9hci8p1u9vyr&st=nuoz2b40&dl=0) of all teaching evaluations (summarized and not) I have received. 

I have taught:

University of San Francisco:

- Applied Statistics in Marketing Intelligence (MSMI 603; 2023—2025; 5 total sections, 20 total credit hours)
- Marketing Analytics I (MSMI 608; 2024—2026; 3 total sections, 6 total credit hours)
- Marketing Analytics II (MSMI 609; 2024—2026; 3 total sections, 6 total credit hours)
- Marketing Analytics (BUS 465; 2024—2026; 3 total sections, 12 total credit hours)
- Marketing Principles (BUS 302; 2025—2026; 2 total sections, 8 total credit hours)

University of Colorado Boulder

- Digital Marketing Tools (MKTG 2700; 2021-2022; 2 total sections, 8 total credit hours)

## Materials

I have linked below a few examples of materials I use in class. This is not exhaustive, as these change frequently.

### Code exercises

- <a href="teaching/R_pcc.qmd" class="btn btn-yellow" role="button">Intro to R</a>
- <a href="teaching/03 Logistic Regression.qmd" class="btn btn-yellow" role="button">Logistic Regression</a>
- <a href="teaching/04 Treatment Effects.qmd" class="btn btn-yellow" role="button">Treatment Effect Estimation</a>

### Slides

- <a href="teaching/06 effect sizes.qmd" class="btn btn-yellow" role="button">Effect Sizes</a>
- <a href="teaching/bias_vs_noise.qmd" class="btn btn-yellow" role="button">Bias vs Noise</a>
- <a href="teaching/03 Correlation and Regression.qmd" class="btn btn-yellow" role="button">Correlation and Regression</a>